name: Build Release

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    name: testes
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-node@v1
      with:
        node-version: '10.15.3'
    - name: Dependências do projeto
      run: yarn install
    - name: "adicionando permissoes"
      run: cd android && chmod a+x gradlew
    - name: "gerar apk"
      run: cd android && ./gradlew assembleRelease && cd ..
    - uses: actions/upload-artifact@v1
      with:
        name: apk-release
        path: android/app/build/outputs/apk/release/app-release.apk
