name: Build Release

on: [push]

jobs:
  testes:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-node@v1
      with:
        node-version: '10.15.3'
    - uses: actions/cache@preview
      id: cache
      with:
        path: node_modules
        key: ${{ runner.os }}-node-${{ hashFiles('**/yarn.lock') }}
        restore-keys: |
          ${{ runner.os }}-node-
    - name: Dependências do projeto
      if: steps.cache.outputs.cache-hit != 'true'
      run: yarn install
    - name: Executar testes
      run: |
        yarn test

  build:
    needs: [testes]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-node@v1
      with:
        node-version: '10.15.3'
    - uses: actions/cache@preview
      id: cache
      with:
        path: node_modules
        key: ${{ runner.os }}-node-${{ hashFiles('**/yarn.lock') }}
        restore-keys: |
          ${{ runner.os }}-node-
    - name: Dependências do projeto
      if: steps.cache.outputs.cache-hit != 'true'
      run: yarn install
    - name: "adicionando permissoes"
      run: cd android && chmod a+x gradlew
    - name: "gerar apk"
      run: cd android && ./gradlew assembleRelease && cd ..
    - uses: actions/upload-artifact@v1
      with:
        name: apk-release
        path: android/app/build/outputs/apk/release/app-release.apk

  gerando_release:
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Bump version and push tag
        uses: wiktorj/github-tag-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
