name: Node.js Package

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: "Run test suite"
        uses: msfjarvis/setup-android@1.0
        with:
          entrypoint: ./android/gradlew
          args: dependencies spotlessApply detekt assembleDebug
