name: Node.js Package

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
      - name: "install dependecie"
        run: yarn
      - name: "chmod" 
        run: chmod a+x ./android/gradlew
      - uses: msfjarvis/setup-android@1.0
        with:
          entrypoint: ./android/gradlew clean
          args: assembleRelease
