name: Node.js Package

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: CHMOD 777 -R
      - name: "Run test suite"
        uses: msfjarvis/setup-android@1.0
      - run: cd android && ./gradlew clean
