name: Node.js Package

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
      - uses: Raul6469/android-gradle-action@1.0.0
        with:
          node-version: 12
      - run: yarn
      - run: yarn clean
      - run: yarn test
      - run: yarn build
