name: Build desenvolvimento

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-java@v1
      with:
        java-version: 11
    - name: "gradlew"
      run: which -a gralde
    - uses: actions/setup-node@v1
      with:
        node-version: '10.15.3'
    - name: Dependências do projeto
      run: yarn install
    - uses: eskatos/gradle-command-action@v1
      with:
        build-root-directory: ./android  
        wrapper-directory: ./android
        arguments: assembleRelease
