name: Node.js Package

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - uses: msfjarvis/setup-android@0.2
      - run: yarn
      - run: chmod +x android/gradlew
      - run: yarn clean
      - run: yarn test
      - run: yarn build
